all: beeper button led pir

beeper: beeper.c
	gcc -o /work/code/beeper/beeper /work/code/beeper/beeper.c -lwiringPi

button: button.c
	gcc -o /work/code/button/button /work/code/button/button.c -lwiringPi

led: led.c
	gcc -o /work/code/led/led /work/code/led/led.c -lwiringPi

pir: pir.c
	gcc -o /work/code/pir/pir /work/code/pir/pir.c -lwiringPi
